# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('song', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('op', models.IntegerField()),
                ('cons', models.IntegerField()),
                ('ex', models.IntegerField()),
                ('ag', models.IntegerField()),
                ('neu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbmrs.Music')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbmrs.User')),
            ],
        ),
    ]
